# Site settings
logo:  <img alt="Moneycle" src="/images/logo.png" height="55" width="174">
title: M<span class='brand-color'>o</span>neycle
email: sir@moneycle.com
description: >
  Don your money monocle (top hats are optional)
  as we explore topics related to money,
  investing and early retirement.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.moneycle.com"
twitter_username: moneymonocle
github_username:  moneycle

# Build settings
markdown: kramdown

paginate: 1

permalink: /:title/
